### ISSUE TITLE
Consider defaulting to not send legacy headers

### ISSUE THREAD

**Issue by emteknetnz** [Firesphere/silverstripe-csp-headers#1]
https://github.com/Firesphere/silverstripe-csp-headers/blob/b6f25897b068c4386932ab7244250d0864e8d7cf/src/Extensions/ControllerCSPExtension.php#L92

Might want to consider making this

$headers = $policy->getHeaders(false);

So that non-csp headers don't get included e.g. 'X-XSS-Protection'

Because it's a little confusing having non csp headers being included in a csp module (even though they're sort of the same thing)

Also it's possible these header have been included in htaccess, and with different values, which may cause unexpected results

**Comment by Firesphere** [comment]
the `.htacess` configuration takes precedence over any PHP set header. Any setting from PHP will be disregarded by Apache and loaded with the `.htaccess` configuration.

I guess that requires documentation.

I'll be updating master soon with a configuration flag for legacy headers with a default to false

**Comment by Firesphere** [comment]
Resolved in https://github.com/Firesphere/silverstripe-csp-headers/commit/79e18b7c5cea744ff94617e47e7ef5b21f9346e3

**Comment by Firesphere** [comment]
Cheers for making me check this @emteknetnz 😄
