### ISSUE TITLE
Allow applying CSP to non live environments

### ISSUE THREAD

**Issue by matt-in-a-hat** [Firesphere/silverstripe-csp-headers#22]
It seems that this module checks either that the env is 'live' or you have to set an explicit cookie to enable CSP output. Ideally there'd be some config way of overriding this e.g. in yaml.

I used to have a custom extension of `ControllerCSPExtension` which overrode `onBeforeInit` to set `$this->addPolicyHeaders = true`, however in your latest version you've moved the checking of `addPolicyHeaders` into the same function where `addPolicyHeaders` is set, so there's no possible way to override without taking/replacing the whole function body.

**Comment by Firesphere** [comment]
Although I do not think, it's a good idea, because it will skew results, a "force_enable" flag, is possible technically.

The reason it's opt-in on Test/Dev systems, is exactly because of that. And I'd like to avoid that.

**Comment by matt-in-a-hat** [comment]
Skew results? Do you mean for reporting?

**Comment by Firesphere** [comment]
Skew rendering, output, and reporting, at the same time
