### ISSUE TITLE
Can't get Nonce to work for me.

### ISSUE THREAD

**Issue by jeremy-hyprnz** [Firesphere/silverstripe-csp-headers#26]
It looks like it's coming from this line, shouldn't it call for `CSPBackend::config()->get('usesNonce')`?

https://github.com/Firesphere/silverstripe-csp-headers/blob/4be1ef1799161d10cf11498c5e6163a188686190/src/Traits/CSPBackendTrait.php#L119

**Comment by Firesphere** [comment]
Yep, that's a typo. Surprised it wasn't picked up by the automated tests...

**Comment by Firesphere** [comment]
This has been resolved in dev-master and will be released soon as a new version
