### ISSUE TITLE
updatesri deleting all but final SRI file?

### ISSUE THREAD

**Issue by matt-in-a-hat** [Firesphere/silverstripe-csp-headers#30]
With this recent change
https://github.com/Firesphere/silverstripe-csp-headers/commit/d275a14fdba4cbee00d8fc1c05e0b094561c67bc#diff-377943dcf6f09ca8a62210e12420f4d600e9d1b4bb59ee2b2eaab4c2643d6a8bR46
Won't this only keep the final file? As it's called for each file? Should it instead be checked in CSPBackend instead?

Also could be worth publishing versions/tags of this module between making changes on master

**Comment by Firesphere** [comment]
Why would it only keep the final file? I'm unsure what your question is about, regarding that change exactly.

Regarding a version. Yes, a new version will be published soon~ish. I do not publish a new version for every little change.

**Comment by matt-in-a-hat** [comment]
If you set `updatesri` then when it loops over all of the JS files for this request it will call `buildSRI` once for each js/css file, so it will call `TRUNCATE SRI` multiple times within 1 request. You're probably better off checking & truncating in `CSPBackend::includeInHTML` before looping the files & gather SRI etc.

**Comment by Firesphere** [comment]
Owwww, hah, I see.

Yes, indeed! I overlooked that when I accepted and merged the PR. Feel free to make a fix-up PR undoing those lines, unless I get to it earlier :)

**Comment by Firesphere** [comment]
Resolved in the latest master branch.
