### ISSUE TITLE
Support the latest Silverstripe version 4.11

### ISSUE THREAD

**Issue by sephyhe** [Firesphere/silverstripe-csp-headers#37]
It seems like the dependencies of this package require `guzzlehttp/guzzle ^6`. However, Silverstripe v4.11 require `guzzlehttp/guzzle ^7 `. I was wondering if it could upgrade to version 7 to support the latest SS?

**Comment by Firesphere** [comment]
Yeah, that should be pretty straight forward, mostly, Guzzle is Guzzle and shouldn't break anything. Probably should be `"guzzlehttp/guzzle": ">5"` in composer.json

**Comment by sephyhe** [comment]
> Yeah, that should be pretty straight forward, mostly, Guzzle is Guzzle and shouldn't break anything. Probably should be `"guzzlehttp/guzzle": ">5"` in composer.json

Thank you to reply me! I made a pull request to update it. Feel free to let me know if there is anything that needs to change.

**Comment by Firesphere** [comment]
Resolved by #38
